# Generated by Django 4.0.4 on 2022-06-20 13:45

from django.db import migrations, models
import notes.models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(storage=notes.models.OverwriteStorage(), upload_to=notes.models.instance),
        ),
    ]
